import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";

const geistPoppins = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"]
})

const geistInter = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
  weight: ["500", "700"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistPoppins.variable} ${geistInter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
